### ISSUE TITLE
Jonny Todo List

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#11]
- [x] Find white image equivalents of pics in home page (which are currently black)

- [x] Source image for news page which is a pic of the Blotter

**Comment by roblotter** [comment]
@JonnyAdaptableTools Also please source an image for social media preview - now the one below is used

![Screenshot 2020-01-07 11 48 56](https://user-images.githubusercontent.com/50020244/71885790-bf48a380-3143-11ea-87b6-1748a9a96976.png)
