### ISSUE TITLE
The action button at the top - all pages - should I think drop down - looking for clean images

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#2]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
Need to unclutter background image/text overlay for all pages - come up with a solution
