### ISSUE TITLE
text blocks on home page not right - mssing one and wanted space for a second image as well to break up text - see proposal on the relevant plan

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#3]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
Add paragraph under top image

**Comment by roblotter** [comment]
Also fix main pitch description

**Comment by roblotter** [comment]
Also need to unclutter background image/text overlay for all pages - come up with a solution
