### ISSUE TITLE
quotes on home page are clients not partners

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#4]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
Make the text " What some of our partners are saying" be able to u[date
