### ISSUE TITLE
AB page - can we lose the descriptions of each function?

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#5]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
Add `url` to functionalities so clicking on the function will open the url

**Comment by roblotter** [comment]
Also move icon on top row and name of function below. need to be able to click the whole box
