### ISSUE TITLE
GG page - can we get rid of the video?

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#6]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
just removed the text in the video field on this page
![Screenshot 2019-12-18 11 02 04](https://user-images.githubusercontent.com/50020244/71071756-d8ce7f00-2185-11ea-8f0b-91c4cfa68869.png)
