### ISSUE TITLE
news and blog stories - where do I input these?  and also I dont see a space for grid guru blog on the page

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#7]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
For adding blog stories, click the "new blog" - see image below
![Screenshot 2019-12-18 15 28 06](https://user-images.githubusercontent.com/50020244/71090226-31644300-21ab-11ea-9317-fe702177bf2d.png)

**Comment by roblotter** [comment]
We need a blog for grid gurus - will be the same place where we write the posts, but will have the `gridguru` tag
