### ISSUE TITLE
Can't see a way to upload more photos/ images for the top of the individual pages

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#8]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by roblotter** [comment]
@JonnyAdaptableTools I made all pages accept an image, check it now
